---
host: 0.0.0.0
scheme: 'http'
servers:
  - name: Server A
    scheme: http
    host: 127.0.0.1
    port: 9800
  - name: Server B
    scheme: http
    host: 127.0.0.1
    port: 9801
  - name: Server C
    scheme: http
    host: 127.0.0.1
    port: 9802
  - name: Server D
    scheme: http
    host: 127.0.0.1
    port: 9803
port: 8888